### ISSUE TITLE
Неправильно определяет корневую папку (WarpGeneratorApp)

### ISSUE THREAD

**Issue by AlIenore31** [GhostRooter0953/discord-voice-ips#14]

**Comment by AlIenore31** [comment]
![изображение_2024-10-13_220014334](https://github.com/user-attachments/assets/82853213-e136-41f5-ba89-69bb31eace1c)

**Comment by GhostRooter0953** [comment]
@MikL9, глянешь? :)

**Comment by GhostRooter0953** [comment]
> ![изображение_2024-10-13_220014334](https://private-user-images.githubusercontent.com/184365963/376045224-82853213-e136-41f5-ba89-69bb31eace1c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5MDY3NTQsIm5iZiI6MTcyODkwNjQ1NCwicGF0aCI6Ii8xODQzNjU5NjMvMzc2MDQ1MjI0LTgyODUzMjEzLWUxMzYtNDFmNS1iYTg5LTY5YmIzMWVhY2UxYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNFQxMTQ3MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MjU5ODc2ZWRlZDJmM2Y4Mzc2YWVjNjRmMjEwYTc4NGUyYWZjMzZmOGNkMWFjMTM5Y2NiNjQ4MTNkNWE0NzQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.NbQ21sbV_qmza49fn33l4M07WBKmjr91gw6yRromPX4)

Вроде как пофиксили

**Comment by AlIenore31** [comment]
Да, работает!
