### ISSUE TITLE
Серверов чуть больше

### ISSUE THREAD

**Issue by kravenrus** [GhostRooter0953/discord-voice-ips#15]
В репозитории от Discord'а только часть IP-адресов (Нидерланды, Россия, Швеция, Италия, Испания, Германия, Румыния), вот тут выкладывал весь перечень диапазонов в аренде для ASN - 49544.

https://pikabu.ru/story/diapazonyi_adresov_arendovannyie_discordom_chto_ispolzuyutsya_serverami_dlya_podderzhki_rabotyi_golosovyikh_kanalov_11907110

**Comment by GhostRooter0953** [comment]
> В репозитории от Discord'а только часть IP-адресов (Нидерланды, Россия, Швеция, Италия, Испания, Германия, Румыния), вот тут выкладывал весь перечень диапазонов в аренде для ASN - 49544.
> 
> https://pikabu.ru/story/diapazonyi_adresov_arendovannyie_discordom_chto_ispolzuyutsya_serverami_dlya_podderzhki_rabotyi_golosovyikh_kanalov_11907110

Нууу, ты прав да, CIDR вытащить это универсально.
Но если подходить к тому, что нам нужно запихнуть в обход только то, что реально используется, то на примере RU региона получается 166 хоста, вместо 510.
Лишнее тащить.. нууу, такое.
Можешь сформировать лист, закинуть в фолдер `discord-voice-ips/custom-solutions/kravenrus` и притащить PR - я солью
