### ISSUE TITLE
Добавить адреса

### ISSUE THREAD

**Issue by ThisIsLamer** [GhostRooter0953/discord-voice-ips#2]
Нашёл дополнительную подсеть
35.213.0.0/16

![image](https://github.com/user-attachments/assets/af30dba6-8142-4638-ba4f-d1b32bcd5643)

**Comment by rekryt** [comment]
Она входит в

35.240.0.0/13
35.208.0.0/12
35.224.0.0/12

![изображение](https://github.com/user-attachments/assets/5ce22374-df9a-47bc-a69f-0bdb379e2c0c)

https://iplist.opencck.org/?format=json&data=cidr4&site=discord.com&site=discord.gg&site=discord.media

**Comment by ThisIsLamer** [comment]
я не нашёл их в адрес листе

![image](https://github.com/user-attachments/assets/9336a385-f5fc-474a-a1d6-46ccbc367b3f)
![image](https://github.com/user-attachments/assets/faa13d9c-ca25-4d8f-b54c-dbb62b14f066)

**Comment by GhostRooter0953** [comment]
> я не нашёл их в адрес листе
> 
> ![image](https://github.com/user-attachments/assets/9336a385-f5fc-474a-a1d6-46ccbc367b3f)
> ![image](https://github.com/user-attachments/assets/faa13d9c-ca25-4d8f-b54c-dbb62b14f066)
> 

А какой регион?

**Comment by ThisIsLamer** [comment]
singapore11121

**Comment by rekryt** [comment]
> я не нашёл их в адрес листе
> 

адрес входит в диапазон 35.208.0.0/12
![изображение](https://github.com/user-attachments/assets/2e78fa5e-d084-4b41-b18c-7801c5621a9a)

**Comment by GhostRooter0953** [comment]
> singapore11121

Ну тут увы, я ж вроде написал серваки каких регионов я добавил)
