### ISSUE TITLE
Добавить ip доменов

### ISSUE THREAD

**Issue by KindWarlock** [GhostRooter0953/discord-voice-ips#3]
Откопанный список на основе discord-domains-list:
```18.239.50.100
18.239.50.52
18.239.50.84
18.239.50.93
23.227.38.74
23.227.38.74
104.17.117.93
104.17.51.93
104.18.20.51
104.18.21.51
104.18.30.128
104.18.31.128
104.18.4.161
104.18.5.161
104.18.8.105
104.18.9.105
104.21.25.51
162.159.128.233
162.159.128.234
162.159.128.235
162.159.129.233
162.159.129.234
162.159.129.235
162.159.130.233
162.159.130.234
162.159.130.235
162.159.133.233
162.159.133.234
162.159.134.233
162.159.134.234
162.159.135.232
162.159.135.233
162.159.135.234
162.159.136.232
162.159.136.233
162.159.136.234
162.159.137.232
162.159.137.233
162.159.137.234
162.159.138.232
162.159.138.233
162.159.138.234
172.67.222.182
188.114.96.0
188.114.97.0
204.11.56.48

**Comment by GhostRooter0953** [comment]
> Откопанный список на основе discord-domains-list:
> 
> ```
> 18.239.50.52
> 18.239.50.84
> 18.239.50.93
> 23.227.38.74
> 23.227.38.74
> 104.17.117.93
> 104.17.51.93
> 104.18.20.51
> 104.18.21.51
> 104.18.30.128
> 104.18.31.128
> 104.18.4.161
> 104.18.5.161
> 104.18.8.105
> 104.18.9.105
> 104.21.25.51
> 162.159.128.233
> 162.159.128.234
> 162.159.128.235
> 162.159.129.233
> 162.159.129.234
> 162.159.129.235
> 162.159.130.233
> 162.159.130.234
> 162.159.130.235
> 162.159.133.233
> 162.159.133.234
> 162.159.134.233
> 162.159.134.234
> 162.159.135.232
> 162.159.135.233
> 162.159.135.234
> 162.159.136.232
> 162.159.136.233
> 162.159.136.234
> 162.159.137.232
> 162.159.137.233
> 162.159.137.234
> 162.159.138.232
> 162.159.138.233
> 162.159.138.234
> 172.67.222.182
> 188.114.96.0
> 188.114.97.0
> 204.11.56.48
> ```

Добавил)
