### ISSUE TITLE
Список стриминговых доменов

### ISSUE THREAD

**Issue by S1lenix** [GhostRooter0953/discord-voice-ips#5]
Есть возможность добавить список из доменов медиа(стриминговых) каналов Discord для регионов?
По типу: russia9345.discord.media

**Comment by iamkuper** [comment]
Список всех адресов/доменов и подсетей уже собрал
https://github.com/iamkuper/amnezia-discord-config

@GhostRooter0953

**Comment by GhostRooter0953** [comment]
> Есть возможность добавить список из доменов медиа(стриминговых) каналов Discord для регионов? По типу: russia9345.discord.media

Насколько я осведомлён, все войсы и стримминг висят на сабдоменах `blabla228.discord.gg`, а любой сабдомен `discord.media` бьётся как сам домен. Следовательно, надо резолвить **GG**

**Comment by GhostRooter0953** [comment]
> Список всех адресов/доменов и подсетей уже собрал https://github.com/iamkuper/amnezia-discord-config
> 
> @GhostRooter0953

Какой варик актуализации этих поддоменов (_следовательно и подсетей_) предлагаешь?

**Comment by iamkuper** [comment]
> > Список всех адресов/доменов и подсетей уже собрал https://github.com/iamkuper/amnezia-discord-config
> > @GhostRooter0953
> 
> Какой варик актуализации этих поддоменов (_следовательно и подсетей_) предлагаешь?

в репозитории скрипт есть - им и собирал)
1) идем по списку локаций 
2) Генерируем в цикле домены [location][id].discord.gg
3) DNS Resolve, если ответил добавляем в файл

**Comment by GhostRooter0953** [comment]
> > > Список всех адресов/доменов и подсетей уже собрал https://github.com/iamkuper/amnezia-discord-config
> > > @GhostRooter0953
> > 
> > 
> > Какой варик актуализации этих поддоменов (_следовательно и подсетей_) предлагаешь?
> 
> в репозитории скрипт есть - им и собирал)
> 
> 1. идем по списку локаций
> 2. Генерируем в цикле домены [location][id].discord.gg
> 3. DNS Resolve, если ответил добавляем в файл

Ну, крч ты нарисовал генератор, типо окей.
Так это, вот [этот список](https://github.com/iamkuper/amnezia-discord-config/tree/main/configs/russia), например, получится скриптом актуализировать? Ты пойми, я просто `жавастриптиз` не перевариваю))) 

upd. Пробежался по твоей репе ещё разок, выглядит красиво, дааа.

**Comment by iamkuper** [comment]
> > > > Список всех адресов/доменов и подсетей уже собрал https://github.com/iamkuper/amnezia-discord-config
> > > > @GhostRooter0953
> > > 
> > > 
> > > Какой варик актуализации этих поддоменов (_следовательно и подсетей_) предлагаешь?
> > 
> > 
> > в репозитории скрипт есть - им и собирал)
> > 
> > 1. идем по списку локаций
> > 2. Генерируем в цикле домены [location][id].discord.gg
> > 3. DNS Resolve, если ответил добавляем в файл
> 
> Ну, крч ты нарисовал генератор, типо окей. Так это, вот [этот список](https://github.com/iamkuper/amnezia-discord-config/tree/main/configs/russia), например, получится скриптом актуализировать? Ты пойми, я просто `жавастриптиз` не перевариваю)))
> 
> upd. Пробежался по твоей репе ещё разок, выглядит красиво, дааа.

минус один - это достаточно долго) но не думаю что придется часто перегенерировать

**Comment by GhostRooter0953** [comment]
> > > > > Список всех адресов/доменов и подсетей уже собрал https://github.com/iamkuper/amnezia-discord-config
> > > > > @GhostRooter0953
> > > > 
> > > > 
> > > > Какой варик актуализации этих поддоменов (_следовательно и подсетей_) предлагаешь?
> > > 
> > > 
> > > в репозитории скрипт есть - им и собирал)
> > > 
> > > 1. идем по списку локаций
> > > 2. Генерируем в цикле домены [location][id].discord.gg
> > > 3. DNS Resolve, если ответил добавляем в файл
> > 
> > 
> > Ну, крч ты нарисовал генератор, типо окей. Так это, вот [этот список](https://github.com/iamkuper/amnezia-discord-config/tree/main/configs/russia), например, получится скриптом актуализировать? Ты пойми, я просто `жавастриптиз` не перевариваю)))
> > upd. Пробежался по твоей репе ещё разок, выглядит красиво, дааа.
> 
> минус один - это достаточно долго) но не думаю что придется часто перегенерировать

Я помониторил эти пару дней, у меня из ~**1457** адресов актуальных осталось **1426**, это из [текущего списка](https://github.com/GhostRooter0953/discord-voice-ips/blob/master/discord-voice-domains-list#L1457). Поэтому да, выглядит будто и нет нужды.
Вообще, я думаю под это дело конкретную машину поднять и распараллелить запросы по сгенерированному списку думаю сразу 100к потенциальных доменов порезолвить. И чтобы он те что резолвятся, динамически тащил сюда, в репу.
