### ISSUE TITLE
Пропущена локация сетей из общего списка, не хватает подсетей.

### ISSUE THREAD

**Issue by ilya7zz** [GhostRooter0953/discord-voice-ips#6]
В общем списке адресов больше чем в разделённых, напр.:  
34.0.248.221
NetRange: 34.0.0.0 - 34.3.2.255
CIDR: 34.2.0.0/16, 34.3.0.0/23, 34.3.2.0/24, 34.0.0.0/15
US Google LLC (GOOGL-2)

Это имеет отношение к дискорду?

Не хватает разбивки на "регион - подсеть", для удобной настройки туннелирования:
russia
66.22.216.0/24
66.22.217.0/24
...
Как это сделал iamkuper =)

**Comment by GhostRooter0953** [comment]
> В общем списке адресов больше чем в разделённых, напр.: 34.0.248.221 NetRange: 34.0.0.0 - 34.3.2.255 CIDR: 34.2.0.0/16, 34.3.0.0/23, 34.3.2.0/24, 34.0.0.0/15 US Google LLC (GOOGL-2)
> 
> Это имеет отношение к дискорду?
> 
> Не хватает разбивки на "регион - подсеть", для удобной настройки туннелирования: russia 66.22.216.0/24 66.22.217.0/24 ... Как это сделал iamkuper =)

Генерить лень, а разбивать на подсети по мне так оверкилл, т.к. лично я, например, пользуюсь IPset и пускаю трафф точечно для всего. 
[Вот](https://github.com/GhostRooter0953/discord-voice-ips/tree/master/ips-by-region) я закинул аналогично по регионам конкретные адреса.

**Comment by GhostRooter0953** [comment]
Я конеш понимаю, что большинство хотят банально запихнуть пару подсетей в какой-нибудь клиент Амнезии, но балин)

**Comment by ilya7zz** [comment]
> Генерить лень, а разбивать на подсети по мне так оверкилл, т.к. лично я, например, пользуюсь IPset и пускаю трафф точечно для всего. [Вот](https://github.com/GhostRooter0953/discord-voice-ips/tree/master/ips-by-region) я закинул аналогично по регионам конкретные адреса.

Я и сообщил о несоответствии общего списка адресов и разделённых на регионы и привёл в пример адрес из общего списка, которого нет в разбитых на регионы.

**Comment by GhostRooter0953** [comment]
Ну, во первых я привёл списки только 5 регионов, а общем их больше
И во вторых, разница в парсинге сутки, то-есть общий список менее актуален, т.к. некоторые адреса уже ни за каким сервером не прибиты.
Поэтому да, такие дела и имеем что имеем.
Добить бы тему с генератором, вот тогда красиво будет. А пока так.

**Comment by GhostRooter0953** [comment]
> Ну, во первых я привёл списки только 5 регионов, а общем их больше И во вторых, разница в парсинге сутки, то-есть общий список менее актуален, т.к. некоторые адреса уже ни за каким сервером не прибиты. Поэтому да, такие дела и имеем что имеем. Добить бы тему с генератором, вот тогда красиво будет. А пока так.

Ну, то-есть я к тому, что не вижу особого смысла добавлять всё и вся (в рамках регионов), т.к. они со временем будут протухать. Нужно сначала довести до ума способ получения актуальных сабдоменов (_тех, что стриминговые_), чтобы это не занимало много времени и не требовало ручного вмешательства.
