### ISSUE TITLE
При добавлении в AmneziaVPN клиент баги с подключением

### ISSUE THREAD

**Issue by S1lenix** [GhostRooter0953/discord-voice-ips#7]
Добавил адреса и домены в раздельное туннелирование amnezia и при подключении в голосовой канал в дискорде, примерно через минут 5-10 проявляются проблемы с подключением. Через браузер не скачиваются файлы, не открывается панель поиска на win11, не запускаются некоторые игры. Пробовал на разных частных серверах: xray, amneziawg и т.д роли не играет.

**Comment by GhostRooter0953** [comment]
Это печально, что тут сказать. Но судя по предоставленной инфе, проблема явно не в списках и т.д.)))
Я бы тут посоветовал сменить тип реализации. Клиент Амнезии вынести на роутер, например.
Ну или если в лом, то попробовать фичу "Раздельное туннелирование приложений":
![image](https://github.com/user-attachments/assets/95be6463-09a8-4e81-96f3-b41008423c49)

**Comment by GhostRooter0953** [comment]
> Клиент Амнезии вынести на роутер, например. 

А рулить списками через `ipset+iptables` (_сам предпочитаю такой способ_)

**Comment by MikL9** [comment]
Можешь попробовать мой способ https://github.com/GhostRooter0953/discord-voice-ips/tree/master/custom-solutions/MikL9/amnezia-warp-builder. Там из предоставленных  @GhostRooter0953  доменов айпишники достаются + какие уже есть бросаются пробрасываются в конфиг. У меня безотказно работает гс и стримы, вроде пока не сталкивался с проблемами

**Comment by S1lenix** [comment]
Решил переходом и настройкой Nekoray
