### ISSUE TITLE
Неполный README у amnezia-warp-builder

### ISSUE THREAD

**Issue by bachelorcthulhu** [GhostRooter0953/discord-voice-ips#8]
В `main.py` лежат следующие пути:
```
    hosts_file = '../discord-domains-list'
    region_directory = '../ips-by-region'
```

Но в директории [`amnezia-warp-builder`](https://github.com/GhostRooter0953/discord-voice-ips/blob/master/custom-solutions/MikL9/amnezia-warp-builder/main.py) таких файлов/папок нет. Может быть добавить в [`README`](https://github.com/GhostRooter0953/discord-voice-ips/tree/28b1a2d2626f53bb1d25cb9234089dd545bb6806/custom-solutions/MikL9/amnezia-warp-builder) откуда пользователь должен взять эти данные? Или добавить в директорию сами эти файлы, чтобы пользователь мог понять, какого вида файла?

Еще пользователь может не понять, что в `.env` надо занести значения из сгенерированного конфига `warp.conf`, а не просто создать файл

**Comment by GhostRooter0953** [comment]
@MikL9, актуализируешь? Я там чутка структуру своих списков поменял и т.д.. Актуализировал бы сам,но прост пока занят.
Или @bachelorcthulhu, если есть желание, можешь притащить PR - я солью.

**Comment by MikL9** [comment]
> @MikL9, актуализируешь? Я там чутка структуру своих списков поменял и т.д.. Актуализировал бы сам,но прост пока занят. Или @bachelorcthulhu, если есть желание, можешь притащить PR - я солью.

Да, как раз видел твой апдейт и собирался)

**Comment by GhostRooter0953** [comment]
Я тут закончил конвертер списков IP в JSON, для тех кто просто хочет в клиентик Amnezia импортировать пару файликов и пустить этот трафф через VPN.

**Comment by MikL9** [comment]
> Я тут закончил конвертер списков IP в JSON, для тех кто просто хочет в клиентик Amnezia импортировать пару файликов и пустить этот трафф через VPN.

Да, отлично. Я как раз думаю переделать под твои скрипты. Запускать твой конвертер для обновления информации через код. И env в exe вынести в небольшой ui тогда, раз это для людей не совсем очевидное поведение с настройкой через файл

**Comment by GhostRooter0953** [comment]
> > Я тут закончил конвертер списков IP в JSON, для тех кто просто хочет в клиентик Amnezia импортировать пару файликов и пустить этот трафф через VPN.
> 
> Да, отлично. Я как раз думаю переделать под твои скрипты. Запускать твой конвертер для обновления информации через код. И env в exe вынести в небольшой ui тогда, раз это для людей не совсем очевидное поведение с настройкой через файл

<3

**Comment by GhostRooter0953** [comment]
Добавил конвертер, обновил доку.
