### ISSUE TITLE
Добавьте гайд на маршрутизацию для Nekoray и прочих VPN клиентов

### ISSUE THREAD

**Issue by VernamRD** [GhostRooter0953/discord-voice-ips#9]
![image](https://github.com/user-attachments/assets/e27abee9-e8e1-4908-927f-fbe3696fe549)
![image](https://github.com/user-attachments/assets/094b4f78-e120-4f23-b1ad-77487679bb3e)

**Comment by GhostRooter0953** [comment]
> ![image](https://github.com/user-attachments/assets/e27abee9-e8e1-4908-927f-fbe3696fe549)
> ![image](https://github.com/user-attachments/assets/094b4f78-e120-4f23-b1ad-77487679bb3e)
> 

Честно, лень этим заниматься)
Репа изначально задумывалась как инфа по доменам/IP, а что с этим делать - каждый должен поуметь сам. 
Но если есть желание - приноси PR с докой, я залью.
